# Generated by Django 3.0.3 on 2020-03-12 18:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import targets.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('picture', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('radius', models.PositiveIntegerField()),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, validators=[targets.validators.validate_coordinates])),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.Topic')),
            ],
        ),
    ]
