# Generated by Django 3.0.3 on 2020-03-16 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_target_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
