# Generated by Django 3.0.3 on 2020-03-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_auto_20200228_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='picture',
            field=models.ImageField(null=True, upload_to='topic_pictures/'),
        ),
    ]
