# Generated by Django 3.0.3 on 2020-03-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_topic_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='picture',
            field=models.TextField(default=''),
        ),
    ]
