# Generated by Django 3.0.3 on 2020-03-23 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0004_target_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='match',
        ),
    ]
