# Generated by Django 3.0.3 on 2020-05-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0005_remove_target_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
