# Generated by Django 3.0.3 on 2020-05-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0008_auto_20200518_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='picture',
            field=models.ImageField(null='topic-pictures/placeholder.png', upload_to='topic-pictures/'),
        ),
    ]
