# Generated by Django 3.0.3 on 2020-05-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0009_auto_20200519_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='picture',
            field=models.ImageField(default='topic-pictures/default-topic.png', upload_to='topic-pictures/'),
        ),
    ]
