# Generated by Django 3.0.3 on 2020-03-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onesignal_playerId',
            field=models.CharField(default='', max_length=40),
        ),
    ]
