# Generated by Django 3.0.3 on 2020-04-06 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_onesignal_playerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='onesignal_playerId',
        ),
    ]
