# Generated by Django 3.0.3 on 2020-04-20 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200417_2310'),
        ('users', '0003_remove_user_onesignal_playerid'),
    ]

    operations = [
    ]
