# Generated by Django 3.0.3 on 2020-05-13 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20200420_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnesignalPlayerId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(default='', max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_ids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
