# Generated by Django 3.0.3 on 2020-05-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='240_F_64678017_zUpiZFjj04cnLri7oADnyMH0XBYyQghG.jpg', upload_to=''),
        ),
    ]
