version: 2
jobs:
  build:
    working_directory: ~/target/
    docker:
      - image: circleci/python:3.7.6-stretch-browsers
        environment:
          CIRCLECI: true
          SECRET_KEY: '!f7k)2j8c!@o!ljx7deoaylhvv)1b$n(np-9l-x7_!4h#*ux*8'
          USER: user
          DB_NAME: target
          PORT: 5432
          DB_ENGINE: django.contrib.gis.db.backends.postgis
          BROKER_URL: redis://localhost:6379
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          ENV_ROLE: CI
          EMAIL_PORT: 587
          PIPENV_VENV_IN_PROJECT: true
      - image: mdillon/postgis
        environment:
          POSTGRES_USER: user
          POSTGRES_DB: target
          POSTGRES_PASSWORD: ""
      - image: redis
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run: sudo apt install -y gdal-bin
      - run: sudo pip3 install -r requirements.txt
      - run: sudo apt-get install redis-server
      - run: sudo redis-server --daemonize yes
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "/"
      - run: python3 manage.py test
      - run: flake8
