# Generated by Django 3.0.3 on 2020-03-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200323_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='chat_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='chat_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_seen',
            field=models.DateTimeField(null=True),
        ),
    ]
