# Generated by Django 3.0.3 on 2020-04-17 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200324_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='date_match',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='date_sent',
            new_name='creation_date',
        ),
    ]
