# Generated by Django 3.0.3 on 2020-03-31 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200324_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='chat_end',
        ),
    ]
