# Generated by Django 3.0.3 on 2020-04-20 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200417_2310'),
        ('chat', '0004_remove_match_chat_end'),
    ]

    operations = [
    ]
